/** Клубы в духе детских СДЮШОР/ДЮСШ и взрослого любительского футбола РФ. */
export type TeamSeedProfile = {
  name: string;
  /** U8, U10, U12, U14, U16, U18, U21, Adult */
  category: string;
  /** 1..5 — сила для сида турниров */
  rating: number;
};

export const TEAM_SEED_PROFILES: TeamSeedProfile[] = [
  { name: 'ДЮСШ «Спартак» 2016', category: 'U8', rating: 5 },
  { name: 'ДЮСШ «Спартак» 2014', category: 'U10', rating: 5 },
  { name: 'ДЮСШ «Спартак» 2012', category: 'U12', rating: 5 },
  { name: 'ДЮСШ «Спартак» 2010', category: 'U14', rating: 5 },
  { name: 'СШ «ЦСКА» 2015', category: 'U9', rating: 5 },
  { name: 'СШ «ЦСКА» 2013', category: 'U11', rating: 5 },
  { name: 'СШ «ЦСКА» 2011', category: 'U13', rating: 5 },
  { name: 'СШ «ЦСКА» 2009', category: 'U15', rating: 5 },
  { name: 'Академия «Зенит» 2014', category: 'U10', rating: 5 },
  { name: 'Академия «Зенит» 2012', category: 'U12', rating: 5 },
  { name: 'Академия «Зенит» 2010', category: 'U14', rating: 5 },
  { name: 'Академия «Зенит» 2008', category: 'U16', rating: 5 },
  { name: 'СДЮШОР «Локомотив» 2013', category: 'U11', rating: 4 },
  { name: 'СДЮШОР «Локомотив» 2011', category: 'U13', rating: 4 },
  { name: 'СДЮШОР «Локомотив» 2009', category: 'U15', rating: 4 },
  { name: 'ФШМ 2014', category: 'U10', rating: 5 },
  { name: 'ФШМ 2012', category: 'U12', rating: 5 },
  { name: 'ФШМ 2010', category: 'U14', rating: 5 },
  { name: 'ДЮФК «Чертаново» 2013', category: 'U11', rating: 4 },
  { name: 'ДЮФК «Чертаново» 2011', category: 'U13', rating: 4 },
  { name: 'РГГРУ им. Смирнова 2012', category: 'U12', rating: 4 },
  { name: 'РГГРУ им. Смирнова 2010', category: 'U14', rating: 4 },
  { name: 'СШОР №45 «Краснодар» 2013', category: 'U11', rating: 4 },
  { name: 'СШОР №45 «Краснодар» 2011', category: 'U13', rating: 4 },
  { name: 'СШОР №45 «Краснодар» 2009', category: 'U15', rating: 4 },
  { name: 'Академия «Ростов» 2012', category: 'U12', rating: 4 },
  { name: 'Академия «Ростов» 2010', category: 'U14', rating: 4 },
  { name: 'ДЮСШ «Динамо» Москва 2014', category: 'U10', rating: 4 },
  { name: 'ДЮСШ «Динамо» Москва 2012', category: 'U12', rating: 4 },
  { name: 'ДЮСШ «Динамо» Москва 2010', category: 'U14', rating: 4 },
  { name: 'СДЮШОР «Динамо» СПб 2013', category: 'U11', rating: 4 },
  { name: 'СДЮШОР «Динамо» СПб 2011', category: 'U13', rating: 4 },
  { name: 'ДЮСШ «Торпедо» 2012', category: 'U12', rating: 3 },
  { name: 'ДЮСШ «Торпедо» 2010', category: 'U14', rating: 3 },
  { name: 'СШ «Рубин» 2013', category: 'U11', rating: 4 },
  { name: 'СШ «Рубин» 2011', category: 'U13', rating: 4 },
  { name: 'Академия «Акрон» 2012', category: 'U12', rating: 3 },
  { name: 'Академия «Акрон» 2010', category: 'U14', rating: 3 },
  { name: 'СДЮШОР «Урал» 2013', category: 'U11', rating: 3 },
  { name: 'СДЮШОР «Урал» 2011', category: 'U13', rating: 3 },
  { name: 'ДЮСШ «Крылья Советов» 2012', category: 'U12', rating: 3 },
  { name: 'ДЮСШ «Крылья Советов» 2010', category: 'U14', rating: 3 },
  { name: 'СШ «Сочи» 2013', category: 'U11', rating: 3 },
  { name: 'СШ «Сочи» 2011', category: 'U13', rating: 3 },
  { name: 'Академия «Балтика» 2012', category: 'U12', rating: 3 },
  { name: 'Академия «Балтика» 2010', category: 'U14', rating: 3 },
  { name: 'ДЮСШ «Ротор» 2013', category: 'U11', rating: 3 },
  { name: 'ДЮСШ «Ротор» 2011', category: 'U13', rating: 3 },
  { name: 'СДЮШОР «Шинник» 2012', category: 'U12', rating: 3 },
  { name: 'СДЮШОР «Шинник» 2010', category: 'U14', rating: 3 },
  { name: 'СШ «Химки» 2013', category: 'U11', rating: 3 },
  { name: 'СШ «Химки» 2011', category: 'U13', rating: 3 },
  { name: 'ДЮСШ «Оренбург» 2012', category: 'U12', rating: 3 },
  { name: 'ДЮСШ «Оренбург» 2010', category: 'U14', rating: 3 },
  { name: 'Академия «Уфа» 2013', category: 'U11', rating: 3 },
  { name: 'Академия «Уфа» 2011', category: 'U13', rating: 3 },
  { name: 'СДЮШОР «Волга» Ульяновск 2012', category: 'U12', rating: 3 },
  { name: 'СДЮШОР «Волга» Ульяновск 2010', category: 'U14', rating: 3 },
  { name: 'ДЮСШ «Томь» 2013', category: 'U11', rating: 2 },
  { name: 'ДЮСШ «Томь» 2011', category: 'U13', rating: 2 },
  { name: 'СШ «Чайка» 2012', category: 'U12', rating: 2 },
  { name: 'СШ «Чайка» 2010', category: 'U14', rating: 2 },
  { name: 'ФК «Строгино» 2011', category: 'U13', rating: 3 },
  { name: 'ФК «Строгино» 2009', category: 'U15', rating: 3 },
  { name: 'ФК «Сокол» Москва 2012', category: 'U12', rating: 3 },
  { name: 'ФК «Сокол» Москва 2010', category: 'U14', rating: 3 },
  { name: 'ФК «Любитель» Подольск', category: 'Adult', rating: 2 },
  { name: 'ФК «Вымпел» Дмитров', category: 'Adult', rating: 2 },
  { name: 'ФК «Алмаз» Анжеро-Судженск', category: 'Adult', rating: 2 },
  { name: 'ФК «Нефтяник» Омск', category: 'Adult', rating: 3 },
  { name: 'ФК «Металлург» Липецк', category: 'Adult', rating: 2 },
  { name: 'ФК «Торпедо» Владимир', category: 'Adult', rating: 3 },
  { name: 'ФК «Динамо» Брянск', category: 'Adult', rating: 3 },
  { name: 'ФК «Спартак» Нальчик', category: 'Adult', rating: 3 },
  { name: 'ФК «КАМАЗ» Набережные Челны', category: 'Adult', rating: 3 },
  { name: 'ФК «Звезда» Пермь', category: 'Adult', rating: 2 },
  { name: 'ФК «Черноморец» Новороссийск', category: 'Adult', rating: 3 },
  { name: 'ФК «Авангард» Курск', category: 'Adult', rating: 2 },
  { name: 'ФК «Лада» Тольятти', category: 'Adult', rating: 2 },
  { name: 'ФК «Торпедо» Миасс', category: 'Adult', rating: 2 },
  { name: 'ФК «Зенит» Ижевск', category: 'Adult', rating: 3 },
  { name: 'ФК «Динамо» Вологда', category: 'Adult', rating: 2 },
  { name: 'ФК «Спартак» Кострома', category: 'Adult', rating: 2 },
  { name: 'ФК «Локомотив» Ярославль', category: 'Adult', rating: 3 },
  { name: 'ФК «Торпедо» Архангельск', category: 'Adult', rating: 2 },
  { name: 'ФК «Динамо» Грозный', category: 'Adult', rating: 3 },
  { name: 'ФК «Ангушт» Назрань', category: 'Adult', rating: 2 },
  { name: 'ФК «Биолог» Тюмень', category: 'Adult', rating: 2 },
  { name: 'ФК «Иртыш» Омск', category: 'Adult', rating: 3 },
  { name: 'ФК «Сибиряк» Братск', category: 'Adult', rating: 2 },
  { name: 'ФК «Сахалин» Южно-Сахалинск', category: 'Adult', rating: 2 },
  { name: 'ФК «Луч» Владивосток', category: 'Adult', rating: 3 },
  { name: 'ФК «Смена» Санкт-Петербург', category: 'Adult', rating: 3 },
  { name: 'ФК «Зенит-2» Санкт-Петербург', category: 'U21', rating: 4 },
  { name: 'ФК «Спартак-2» Москва', category: 'U21', rating: 4 },
  { name: 'ФК «ЦСКА-2» Москва', category: 'U21', rating: 4 },
  { name: 'ФК «Краснодар-2»', category: 'U21', rating: 4 },
  { name: 'ФК «Ростов-2»', category: 'U21', rating: 3 },
  { name: 'ФК «Рубин-2» Казань', category: 'U21', rating: 3 },
  { name: 'МФК «Корона» Москва', category: 'Adult', rating: 2 },
  { name: 'МФК «Город» Нижний Новгород', category: 'Adult', rating: 2 },
  { name: 'ФК «Прогресс» Бийск', category: 'Adult', rating: 2 },
  { name: 'ФК «Колос» Покровское', category: 'Adult', rating: 2 },
  { name: 'ФК «Урожай» Канск', category: 'Adult', rating: 1 },
  { name: 'ФК «Гранит» Троицк', category: 'Adult', rating: 2 },
  { name: 'ФК «Олимп» Киров', category: 'Adult', rating: 2 },
  { name: 'ФК «Восток» Улан-Удэ', category: 'Adult', rating: 2 },
  { name: 'ФК «Амур» Благовещенск', category: 'Adult', rating: 2 },
  { name: 'ФК «Дружба» Майкоп', category: 'Adult', rating: 2 },
  { name: 'ФК «Строитель» Уфа', category: 'Adult', rating: 2 },
  { name: 'ФК «Газовик» Оренбург', category: 'Adult', rating: 2 },
  { name: 'ФК «Темп» Барнаул', category: 'Adult', rating: 2 },
  { name: 'ФК «Энергия» Чита', category: 'Adult', rating: 1 },
  { name: 'ФК «Полёт» Курган', category: 'Adult', rating: 2 },
  { name: 'ФК «Торпедо» Рубцовск', category: 'Adult', rating: 1 },
  { name: 'ФК «Шахтёр» Кемерово', category: 'Adult', rating: 2 },
  { name: 'ФК «Металлург» Новокузнецк', category: 'Adult', rating: 2 },
  { name: 'ФК «Угольщик» Прокопьевск', category: 'Adult', rating: 1 },
  { name: 'ФК «Старт» Самара', category: 'Adult', rating: 2 },
  { name: 'ФК «Волгарь» Астрахань', category: 'Adult', rating: 2 },
  { name: 'ФК «Дружба» Волгоград', category: 'Adult', rating: 2 },
  { name: 'ФК «Кубань» Холмская', category: 'Adult', rating: 2 },
  { name: 'ФК «Терек» Газопром', category: 'Adult', rating: 3 },
  { name: 'ФК «Алания» Владикавказ', category: 'Adult', rating: 3 },
  { name: 'ФК «Дагестан» Махачкала', category: 'Adult', rating: 2 },
  { name: 'ФК «Легенда» Калининград', category: 'Adult', rating: 2 },
  { name: 'ФК «Псков»', category: 'Adult', rating: 2 },
  { name: 'ФК «Новгород»', category: 'Adult', rating: 2 },
  { name: 'ФК «Мурманск»', category: 'Adult', rating: 2 },
  { name: 'ФК «Север» Мончегорск', category: 'Adult', rating: 1 },
  { name: 'ФК «Полюс» Магадан', category: 'Adult', rating: 1 },
];

export const TEAM_SEED_PROFILES_UNIQ = TEAM_SEED_PROFILES.filter(
  (profile, index, list) =>
    list.findIndex((p) => p.name === profile.name) === index,
);
