import { StyleSheet } from 'react-native'
import type { ThemeColors } from './palette'

export function createMatchProtocolStyles(colors: ThemeColors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.background },
    flex: { flex: 1 },
    scroll: { padding: 16, paddingBottom: 32 },
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    emptyMatchWrap: { flex: 1, paddingHorizontal: 16, paddingTop: 8, justifyContent: 'center' },
    emptyMatchBack: { marginTop: 8, maxWidth: 320, alignSelf: 'center', width: '100%' },
    noticeBlock: { marginBottom: 12 },
    protocolTabBar: {
      flexDirection: 'row',
      marginBottom: 16,
      padding: 4,
      borderRadius: 14,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    protocolTab: {
      flex: 1,
      paddingVertical: 11,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 10,
    },
    protocolTabActive: {
      backgroundColor: colors.background,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.12,
      shadowRadius: 3,
      elevation: 2,
    },
    protocolTabText: { fontSize: 15, fontWeight: '600', color: colors.muted },
    protocolTabTextActive: { color: colors.accent },
    rosterTabHint: {
      fontSize: 12,
      color: colors.muted,
      marginBottom: 12,
      lineHeight: 17,
    },
    matchHeader: { marginBottom: 4 },
    time: { fontSize: 12, color: colors.muted, marginBottom: 6, letterSpacing: 0.2 },
    teams: { fontSize: 20, fontWeight: '700', color: colors.primary, lineHeight: 26, letterSpacing: -0.3 },
    /** Карточка табло: счёт и подпись про голы — одним блоком, без «ломаных» колонок */
    scoreBoard: {
      marginTop: 16,
      marginBottom: 22,
      padding: 16,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    scoreAutoPill: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 14,
    },
    scoreAutoPillText: { fontSize: 12, fontWeight: '600', color: colors.accent },
    scoreBoardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    scoreTeamCol: { flex: 1, alignItems: 'center', minWidth: 0 },
    scoreLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.muted,
      marginBottom: 8,
      letterSpacing: 0.4,
      textTransform: 'uppercase' as const,
    },
    scoreInput: {
      width: '100%',
      maxWidth: 112,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 8,
      fontSize: 28,
      fontWeight: '700',
      textAlign: 'center',
      color: colors.text,
    },
    scoreInputMuted: {
      opacity: 0.88,
      backgroundColor: colors.background,
    },
    scoreFootnote: {
      marginTop: 14,
      fontSize: 12,
      color: colors.muted,
      textAlign: 'center',
      lineHeight: 17,
      paddingHorizontal: 4,
    },
    colon: {
      fontSize: 26,
      fontWeight: '700',
      color: colors.primary,
      paddingHorizontal: 6,
      marginBottom: 8,
    },
    row: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'center', marginBottom: 20 },
    colonSmall: { fontSize: 18, fontWeight: '700', paddingHorizontal: 8, paddingBottom: 8 },
    label: { fontSize: 12, fontWeight: '700', color: colors.muted, marginBottom: 10, letterSpacing: 0.3 },
    chipsScroll: { marginBottom: 4, flexGrow: 0 },
    chips: { flexDirection: 'row', flexWrap: 'nowrap', alignItems: 'center', paddingVertical: 2, gap: 8 },
    teamChipsCol: { flexDirection: 'column', gap: 10, marginBottom: 12 },
    /** Две команды в одну строку в модалке события */
    teamChipsRow: { flexDirection: 'row', gap: 8, marginBottom: 12, alignItems: 'stretch' },
    teamChipFull: { alignSelf: 'stretch' },
    teamChipHalf: { flex: 1, minWidth: 0, justifyContent: 'center' },
    minuteControlRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 10,
    },
    minuteStepBtn: {
      width: 48,
      height: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    minuteValueInput: {
      flex: 1,
      minWidth: 0,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 8,
      fontSize: 22,
      fontWeight: '700',
      textAlign: 'center',
      color: colors.text,
    },
    minutePresetsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
    minutePresetBtn: {
      flexGrow: 1,
      flexBasis: '21%',
      minWidth: 72,
      paddingVertical: 11,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    minutePresetText: { fontSize: 14, fontWeight: '700', color: colors.accent },
    chip: {
      paddingVertical: 10,
      paddingHorizontal: 14,
      /** Как у полей минуты / выбора игрока (12), без «таблеточного» 22 */
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      minHeight: 42,
      justifyContent: 'center',
    },
    chipActive: {
      borderColor: colors.accent,
      backgroundColor: colors.background,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.35,
      shadowRadius: 6,
      elevation: 3,
    },
    chipDisabled: { opacity: 0.5 },
    chipText: { fontSize: 13, color: colors.muted },
    chipTextActive: { color: colors.accent, fontWeight: '600' },
    eventsSection: { marginBottom: 16 },
    eventsTitle: { fontSize: 15, fontWeight: '600', color: colors.primary, marginBottom: 4 },
    eventsSub: { fontSize: 12, color: colors.muted, marginBottom: 10, lineHeight: 16 },
    eventsEmpty: { fontSize: 14, color: colors.muted, marginBottom: 8 },
    evRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      marginBottom: 8,
      backgroundColor: colors.surface,
    },
    evMain: { flex: 1, padding: 10 },
    evText: { fontSize: 14, color: colors.text },
    evType: { fontSize: 11, color: colors.muted, marginTop: 2 },
    evDel: { padding: 12 },
    evDelText: { fontSize: 16, color: colors.error },
    addEvBtn: {
      alignSelf: 'flex-start',
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.accent,
      marginTop: 4,
    },
    addEvBtnText: { color: colors.accent, fontWeight: '600', fontSize: 14 },
    events: {
      marginBottom: 20,
      padding: 12,
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    eventsHint: { fontSize: 11, color: colors.muted, marginBottom: 10, lineHeight: 15 },
    rosterSection: {
      marginBottom: 18,
      padding: 4,
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    rosterSectionTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.primary,
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 4,
    },
    rosterSectionSub: {
      fontSize: 12,
      color: colors.muted,
      paddingHorizontal: 14,
      paddingBottom: 12,
      lineHeight: 16,
    },
    rosterTeamCard: {
      marginHorizontal: 10,
      marginBottom: 10,
      padding: 12,
      borderRadius: 12,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
    },
    rosterTeamCardFirst: { marginTop: 4 },
    rosterSideLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.primary,
      marginBottom: 10,
    },
    rosterSideSpacer: { marginTop: 2 },
    rosterPlayerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    rosterPlayerRowLast: { borderBottomWidth: 0 },
    rosterBullet: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.accent,
      marginRight: 12,
      opacity: 0.85,
    },
    rosterLine: { fontSize: 14, color: colors.text, flex: 1, lineHeight: 20 },
    evLine: { fontSize: 13, color: colors.text, marginBottom: 4 },
    playoffBox: {
      marginBottom: 16,
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    playoffTitle: { fontSize: 15, fontWeight: '600', color: colors.primary, marginBottom: 6 },
    playoffHint: { fontSize: 12, color: colors.muted, marginBottom: 10, lineHeight: 17 },
    miniLabel: { fontSize: 12, fontWeight: '600', color: colors.primary, marginBottom: 6, marginTop: 8 },
    smallInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 10,
      fontSize: 16,
      textAlign: 'center',
    },
    field: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 10,
      fontSize: 15,
      marginBottom: 8,
    },
    fieldMultiline: { minHeight: 72, textAlignVertical: 'top' },
    fieldBtn: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      marginBottom: 8,
      backgroundColor: colors.background,
    },
    fieldBtnText: { fontSize: 15, color: colors.text, flex: 1, paddingRight: 8 },
    fieldBtnRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    fieldBtnDisabled: { opacity: 0.45 },
    modalKeyboardRoot: { flex: 1 },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(15, 23, 42, 0.45)',
      justifyContent: 'flex-end',
      position: 'relative',
    },
    modalSheetSafe: { maxHeight: '92%', width: '100%' },
    pickerOverlayRoot: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 1000,
      elevation: 1000,
    },
    pickerDimFull: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(15, 23, 42, 0.35)',
    },
    pickerSheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      maxHeight: '78%',
      backgroundColor: colors.background,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 32,
      elevation: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
    },
    pickerList: { flexGrow: 0, maxHeight: 380 },
    modalCard: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      padding: 16,
      maxHeight: '90%',
    },
    modalTitle: { fontSize: 18, fontWeight: '700', color: colors.primary, marginBottom: 8 },
    pickerHint: { fontSize: 12, color: colors.muted, marginBottom: 10 },
    modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, marginTop: 16 },
    modalBtn: {
      backgroundColor: colors.accent,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 12,
    },
    modalBtnText: { color: colors.onAccent, fontWeight: '600', fontSize: 15 },
    modalBtnGhost: { paddingVertical: 12, paddingHorizontal: 12 },
    modalBtnGhostText: { color: colors.muted, fontWeight: '600', fontSize: 15 },
    pickerRow: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.border },
    pickerRowDisabled: { opacity: 0.45 },
    pickerRowText: { fontSize: 16, color: colors.text },
    pickerRowTextDisabled: { color: colors.muted },
  })
}
