/**
 * Подписи кодов `action` в журнале аудита (синхронно с backend `admin-audit-human-action.ts`
 * + запасные `http.*` из общего fallback разбора пути).
 */
export const AUDIT_LOG_ACTION_LABELS: Record<'ru' | 'en', Record<string, string>> = {
  ru: {
    'tournament.gallery_reorder': 'Переупорядочена галерея турнира',
    'tournament.gallery_update': 'Изменено изображение галереи',
    'tournament.gallery_delete': 'Удалено изображение галереи',
    'tournament.gallery_create': 'Добавлено изображение в галерею турнира',
    'tournament.news_update': 'Изменена новость',
    'tournament.news_delete': 'Удалена новость',
    'tournament.news_create': 'Создана новость турнира',
    'tenant.news_update': 'Изменена новость организации',
    'tenant.news_delete': 'Удалена новость организации',
    'tenant.news_create': 'Создана новость организации',
    'tenant.news_tag_update': 'Изменён тег новостей',
    'tenant.news_tag_delete': 'Удалён тег новостей',
    'tenant.news_tag_create': 'Создан тег новостей',
    'tenant.match_schedule_reason_update':
      'Изменена причина переноса или отмены матча',
    'tenant.match_schedule_reason_delete':
      'Удалена причина переноса или отмены матча',
    'tenant.match_schedule_reason_create':
      'Создана причина переноса или отмены матча',
    'tournament.round_reorder': 'Переупорядочены раунды турнира',
    'tournament.match_protocol_update': 'Обновлён протокол матча',
    'tournament.match_update': 'Изменён матч',
    'tournament.match_delete': 'Удалён матч',
    'tournament.match_create': 'Создан матч турнира',
    'standalone.match_protocol_update': 'Обновлён протокол матча',
    'standalone.match_update': 'Изменён матч',
    'standalone.match_delete': 'Удалён матч',
    'standalone.match_attach_tournament': 'Матч привязан к турниру',
    'tournament.match_detach': 'Матч отвязан от турнира',
    'standalone.match_create': 'Создан матч',
    'tournament.teams_group_layout_sync': 'Синхронизирована раскладка групп турнира',
    'tournament.team_set_group': 'Задана группа команде',
    'tournament.team_set_rating': 'Обновлён рейтинг команде',
    'tournament.team_add': 'Команда добавлена в турнир',
    'tournament.team_remove': 'Команда удалена из турнира',
    'tournament.calendar_generate': 'Сгенерирован календарь',
    'tournament.calendar_clear': 'Очищен календарь турнира',
    'tournament.playoff_generate': 'Сгенерирован плей-офф турнира',
    'tournament.create': 'Создан турнир',
    'tournament.update': 'Изменён турнир',
    'tournament.delete': 'Удалён турнир',
    'tournament.table_read': 'Просмотр таблицы турнира',
    'tournament.news_list_read': 'Просмотр списка новостей турнира',
    'tournament.read': 'Просмотр турнира',
    'tenant.tournament_list_read': 'Просмотр списка турниров',
    'tenant.news_list_read': 'Просмотр списка новостей',
    'tenant.news_tags_list_read': 'Просмотр тегов новостей',
    'tenant.matches_list_read': 'Просмотр матчей',
    'tenant.standalone_matches_list_read': 'Просмотр одиночных матчей',
    'http.delete': 'HTTP DELETE (общий запрос)',
    'http.get': 'HTTP GET (общий запрос)',
    'http.head': 'HTTP HEAD (общий запрос)',
    'http.options': 'HTTP OPTIONS (общий запрос)',
    'http.patch': 'HTTP PATCH (общий запрос)',
    'http.post': 'HTTP POST (общий запрос)',
    'http.put': 'HTTP PUT (общий запрос)',
  },
  en: {
    'tournament.gallery_reorder': 'Tournament gallery reordered',
    'tournament.gallery_update': 'Gallery image updated',
    'tournament.gallery_delete': 'Gallery image removed',
    'tournament.gallery_create': 'Image added to tournament gallery',
    'tournament.news_update': 'Tournament news updated',
    'tournament.news_delete': 'Tournament news deleted',
    'tournament.news_create': 'Tournament news created',
    'tenant.news_update': 'Organization news updated',
    'tenant.news_delete': 'Organization news deleted',
    'tenant.news_create': 'Organization news created',
    'tenant.news_tag_update': 'News tag updated',
    'tenant.news_tag_delete': 'News tag deleted',
    'tenant.news_tag_create': 'News tag created',
    'tenant.match_schedule_reason_update': 'Match schedule reason updated',
    'tenant.match_schedule_reason_delete': 'Match schedule reason deleted',
    'tenant.match_schedule_reason_create': 'Match schedule reason created',
    'tournament.round_reorder': 'Tournament rounds reordered',
    'tournament.match_protocol_update': 'Match protocol updated',
    'tournament.match_update': 'Match updated',
    'tournament.match_delete': 'Match deleted',
    'tournament.match_create': 'Tournament match created',
    'standalone.match_protocol_update': 'Match protocol updated',
    'standalone.match_update': 'Match updated',
    'standalone.match_delete': 'Match deleted',
    'standalone.match_attach_tournament': 'Match linked to tournament',
    'tournament.match_detach': 'Match unlinked from tournament',
    'standalone.match_create': 'Match created',
    'tournament.teams_group_layout_sync': 'Tournament group layout synced',
    'tournament.team_set_group': 'Team group set',
    'tournament.team_set_rating': 'Team rating updated',
    'tournament.team_add': 'Team added to tournament',
    'tournament.team_remove': 'Team removed from tournament',
    'tournament.calendar_generate': 'Calendar generated',
    'tournament.calendar_clear': 'Tournament calendar cleared',
    'tournament.playoff_generate': 'Playoff bracket generated',
    'tournament.create': 'Tournament created',
    'tournament.update': 'Tournament updated',
    'tournament.delete': 'Tournament deleted',
    'tournament.table_read': 'Tournament table viewed',
    'tournament.news_list_read': 'Tournament news list viewed',
    'tournament.read': 'Tournament viewed',
    'tenant.tournament_list_read': 'Tournament list viewed',
    'tenant.news_list_read': 'News list viewed',
    'tenant.news_tags_list_read': 'News tags viewed',
    'tenant.matches_list_read': 'Matches viewed',
    'tenant.standalone_matches_list_read': 'Standalone matches viewed',
    'http.delete': 'HTTP DELETE (generic)',
    'http.get': 'HTTP GET (generic)',
    'http.head': 'HTTP HEAD (generic)',
    'http.options': 'HTTP OPTIONS (generic)',
    'http.patch': 'HTTP PATCH (generic)',
    'http.post': 'HTTP POST (generic)',
    'http.put': 'HTTP PUT (generic)',
  },
}

/** Все коды для фильтра (порядок задаётся при сборке опций). */
export const AUDIT_LOG_ACTION_CODES: readonly string[] = Object.keys(
  AUDIT_LOG_ACTION_LABELS.ru,
)
